config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'homes#top'
  get 'foods/index'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  resources :users, only: [:show, :destroy]
  resources :articles, only: [:index, :show]
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :image, presence: true
  validates :title, presence: true, length: {maximum: 20}
  validates :description, presence: true, length: {maximum: 60}
  validates :people, presence: true

  belongs_to :user

  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :new, :search]
  def index
    @recipes = Recipe.includes(:user).order(id: "DESC")
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.steps.build
    @recipe.ingredients.build
    unless user_signed_in?
      flash[:notice] = "レシピ投稿にはログインが必要です"
    end
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:notice] = "レシピを投稿しました"
      redirect_to @recipe
    else
      render 'recipes/new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:notice] = "レシピを更新しました"
      redirect_to @recipe
    else
      render 'recipes/edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'レシピは削除されました'
    redirect_to root_path
  end

  def search
    @keyword = params[:keyword]
    if @keyword.present?
      @recipes = Recipe.includes(:steps, :ingredients).references(:steps, :ingredients)
      @keyword.split(/[[:blank:]]+/).each do |k|
        next if k == ""
        @recipes =  @recipes.where('title like :q OR description like :q OR name like :q OR content like :q', q: "%#{k}%")
      end
    else
      @recipes = Recipe.order(id: "DESC")
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, :people, steps_attributes: [:id, :number, :content, :_destroy], ingredients_attributes: [:id, :name, :amount, :_destroy])
  end
end

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <div class="row mb-3 g-3">
    <div class="col-sm-7">
      <%= f.text_field :name, class: "form-control", placeholder:"材料名" %>
    </div>
    <div class="col-sm">
      <%= f.text_field :amount, class: "form-control", placeholder:"量" %>
    </div>
    <div class="col-sm">
      <%= link_to_remove_association f do %>
        <i class="fas fa-times-circle"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields">
  <div class="row mb-3 g-3">
    <div class="col-sm number">
      <%= f.number_field :number, class: "form-control", placeholder:"順番" %>
    </div>
    <div class="col-sm-7">
      <%= f.text_area :content, class: "form-control", placeholder:"作り方", rows:"3" %>
    </div>
    <div class="col-sm">
      <%= link_to_remove_association f do %>
        <i class="fas fa-times-circle"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h4 class="mb-5 title"><strong>Fodmapレシピを投稿</strong></h4>

<div class="new">
  <%= form_with(model: @recipe, local:true) do |f| %>
    <%= render "layouts/error_messages", model: f.object %>

    <div class="container">
      <div class="row">
        <div class="col-sm">
          <strong><%= f.label :image, '写真', class: "form-label sub-title" %></strong>
          <%= f.file_field :image, class: 'img_field', style: 'display:none;' %>
          <% if @recipe.image? %>
            <%= image_tag @recipe.image.url, onClick: "$('.img_field').click()", class: 'img-thumbnail img_prev' %>
          <% else %>
            <%= image_tag asset_path("sample.png"), class:"img-thumbnail img_prev", onClick:"$('.img_field').click()" %>
          <% end %>
        </div>
        <div class="col-sm">
          <div class="box1">
            <strong><%= f.label :title, '料理名', class: "form-label sub-title" %></strong>
            <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
          </div>
          <div class="box2">
            <strong><%= f.label :description, 'コメント', class: "form-label sub-title" %></strong>
            <%= f.text_area :description, placeholder: "コメント", class: "form-control text" %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-10 offset-md-1">
      <div class="container mt-5">
        <p class="mb-3 sub-title"><strong>材料</strong></p>
        <div class="jojo">
          <%= f.text_field :people, class:"form-control people", placeholder:"何人分" %>
        </div>
        <span> 例)２人分</span>
        <%= f.fields_for :ingredients do |i| %>
          <%= render "ingredient_fields", f: i %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "追加", f, :ingredients, class:"btn botton" %>
        </div>
      </div>
    </div>

    <div class="col-md-10 offset-md-1 mt-5">
      <div class="container mt-3">
        <p class="mb-3 sub-title"><strong>作り方</strong></p>
        <%= f.fields_for :steps do |s| %>
          <%= render "step_fields", f: s %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "追加", f, :steps, class:"btn botton" %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="btn-container col-sm-5 offset-sm-2">
          <%= f.submit '更新', class:"new-btn" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'image_preview' %>

app/views/recipes/index.html.erb
<div class="search-set mb-5 pb-3">
  <h5 class="title"><strong>低FODMAPレシピを検索</strong></h5>
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <div class="search_con mt-3">
          <%= form_with url: search_recipes_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, placeholder: "料理名・食材でレシピをさがす", value:@keyword %>
            <input type="submit" value="&#xf002">
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<h4 class="mb-5 title"><strong>レシピ一覧</strong></h4>
<div class="box">
  <% @recipes.each do |r| %>
    <%= link_to r do %>
      <div class="box-content">
        <%= image_tag r.image.url, class:"recipe-photo" %>
        <p class="recipe-title"><%= r.title %></p>
        <div class="ingredient-box">
          <% r.ingredients.each do |i| %>
            <span><%= i.name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h3 class="mb-5 title"><strong>Fodmapレシピを投稿</strong></h3>

<div class="new">
  <%= form_with(model: @recipe, local:true) do |f| %>
    <%= render "layouts/error_messages", model: f.object %>

    <div class="container">
      <div class="row">
        <div class="col-sm">
          <strong><%= f.label :image, '写真', class: "form-label sub-title" %></strong>
          <%= f.file_field :image, class: 'img_field', style: 'display:none;' %>
          <% if @recipe.image? %>
            <%= image_tag @recipe.image.url, onClick: "$('.img_field').click()", class: 'img-thumbnail img_prev' %>
          <% else %>
            <%= image_tag asset_path("sample.png"), class:"img-thumbnail img_prev", onClick:"$('.img_field').click()" %>
          <% end %>
        </div>
        <div class="col-sm">
          <div class="box1">
            <strong><%= f.label :title, '料理名', class: "form-label sub-title" %></strong>
            <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
          </div>
          <div class="box2">
            <strong><%= f.label :description, 'コメント', class: "form-label sub-title" %></strong>
            <%= f.text_area :description, placeholder: "コメント", class: "form-control text" %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-10 offset-md-1">
      <div class="container mt-5">
        <p class="mb-3 sub-title"><strong>材料</strong></p>
        <div class="jojo">
          <%= f.text_field :people, class:"form-control people", placeholder:"何人分" %>
        </div>
        <span> 例)２人分</span>
        <%= f.fields_for :ingredients do |i| %>
          <%= render "ingredient_fields", f: i %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "追加", f, :ingredients, class:"btn botton" %>
        </div>
      </div>
    </div>

    <div class="col-md-10 offset-md-1 mt-5">
      <div class="container mt-3">
        <p class="mb-3 sub-title"><strong>作り方</strong></p>
        <%= f.fields_for :steps do |s| %>
          <%= render "step_fields", f: s %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "追加", f, :steps, class:"btn botton" %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="btn-container col-sm-5 offset-sm-2">
          <%= f.submit '投稿', class:"new-btn" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'image_preview' %>

app/views/recipes/search.html.erb
<h3 class="mb-5 title"><strong>「<%= @keyword %>」の検索結果</strong></h3>

<div class="box">
  <% @recipes.each do |r| %>
    <%= link_to r do %>
      <div class="box-content">
        <%= image_tag r.image.url, class:"recipe-photo" %>
        <p class="recipe-title"><%= r.title %></p>
        <div class="ingredient-box">
          <% r.ingredients.each do |i| %>
            <span><%= i.name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<% unless @recipes.present? %>
  <h4 class="mt-5 text-center"><strong>該当するレシピはありませんでした</strong></h4>
  <h5 class="pt-2 text-center">別のキーワードで探してみてください</h5>
<% end %>

app/views/recipes/show.html.erb
<div class="container search-set mb-5">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="search_con">
        <%= form_with url: search_recipes_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, placeholder: "料理名・食材でレシピをさがす", value:@keyword %>
          <input type="submit" value="&#xf002">
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if @recipe.user === current_user %>
      <div class="right">
        <%= link_to edit_recipe_path(@recipe) do %>
          編集 |
        <% end %>
        <%= link_to @recipe, method: :delete, data: {confirm: "レシピを削除しますか？"} do %>
          削除
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm">
      <h3 class="mb-5 title"><strong><%= @recipe.title %></strong></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <%= image_tag @recipe.image.url, class: 'img-thumbnail' %>
      <% if user_signed_in? %>
        <div id="favorites_buttons_<%= @recipe.id %>">
          <%= render 'favorites/favorite', recipe: @recipe %>
        </div>
      <% else %>
        <%= link_to recipe_favorites_path(@recipe), method: :post do %>
          <button type="button" class="button1 mt-3 mb-3" ><i class="far fa-heart"></i> お気に入り <%= @recipe.favorites.count %></button>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm">
      <p class="pt-2 pb-1"><%= @recipe.description %></p>
      <p class="pb-3">投稿者：<%= link_to @recipe.user.name, @recipe.user %>さん</p>
      <span class="h5"><strong>材料</strong></span><span> (<%= @recipe.people %>)</span>
      <table class="table mt-2">
        <tbody>
          <% @recipe.ingredients.each do |i| %>
          <tr>
            <td><%= i.name %></td>
            <td><%= i.amount %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mt-3">
    <h5><strong>作り方</strong></h5>
    <table class="table mt-2">
      <tbody>
        <% @recipe.steps.each do |s| %>
        <tr class="table-recipe">
          <th scope="row" class="table-number"><%= s.number %>.</th>
          <td><%= s.content %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>