config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'homes#top'
  get 'foods/index'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  resources :users, only: [:show, :destroy]
  resources :articles, only: [:index, :show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :name, presence: true, length: {maximum: 20}
  validates :amount, presence: true, length: {maximum: 20}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :image, presence: true
  validates :title, presence: true, length: {maximum: 20}
  validates :description, presence: true, length: {maximum: 60}
  validates :people, presence: true

  belongs_to :user

  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe

  validates :number, presence: true
  validates :content, presence: true, length: {maximum: 60}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :recipes, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # deviseのuserカラムに name を追加している場合は以下のコメントアウトも追記します
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  has_many :favorites, dependent: :destroy
  has_many :myfavorites, through: :favorites, source: :recipe

  def already_favorited?(recipe)
    self.favorites.exists?(recipe_id: recipe.id)
  end

  def total_fav
    total = 0
    self.myfavorites.each do |f|
      total += f.favorites.count
    end
    return total
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @favorite = current_user.favorites.create(recipe_id: params[:recipe_id])
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
    favorite.destroy
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @new = Recipe.limit(3).order('id DESC')
    @ranking = Recipe.includes(:favorited_users).sort{|a,b| b.favorited_users.size <=> a.favorited_users.size}.first(3)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :new, :search]
  def index
    @recipes = Recipe.includes(:user).order(id: "DESC")
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.steps.build
    @recipe.ingredients.build
    unless user_signed_in?
      flash[:notice] = "レシピ投稿にはログインが必要です"
    end
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:notice] = "レシピを投稿しました"
      redirect_to @recipe
    else
      render 'recipes/new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:notice] = "レシピを更新しました"
      redirect_to @recipe
    else
      render 'recipes/edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'レシピは削除されました'
    redirect_to root_path
  end

  def search
    @keyword = params[:keyword]
    if @keyword.present?
      @recipes = Recipe.includes(:steps, :ingredients).references(:steps, :ingredients)
      @keyword.split(/[[:blank:]]+/).each do |k|
        next if k == ""
        @recipes =  @recipes.where('title like :q OR description like :q OR name like :q OR content like :q', q: "%#{k}%")
      end
    else
      @recipes = Recipe.order(id: "DESC")
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, :people, steps_attributes: [:id, :number, :content, :_destroy], ingredients_attributes: [:id, :name, :amount, :_destroy])
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if current_user == @user
      @user.destroy
      flash[:notice] = "ユーザー情報は全て削除されました"
      redirect_to root_path
    else
      flash[:danger] = "不正なアクセスです"
      redirect_back (fall_back root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/homes/top.html.erb
<div class="search-set mb-5 pb-3">
  <h5 class="title"><strong>低FODMAPレシピを検索</strong></h5>
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <div class="search_con mt-3">
          <%= form_with url: search_recipes_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, placeholder: "料理名・食材でレシピをさがす", value:@keyword %>
            <input type="submit" value="&#xf002">
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<h5 class="title"><strong>低FODMAP(フォドマップ)食とは？</strong></h5>
<p class="what-fod">
  下痢や便秘が続くと腸の健康が乱れ、肌荒れ、肩こりなど様々な症状を引き起こします。<br>
  そんな症状が続く方は「過敏性腸症候群」かもしれません。<br>
  そんな過敏性腸症候群の75～80％の方に改善が見られた方法、それが「低FODMAP食」です。<br>
  FODMAPとは４種類の発酵性の糖質の頭文字をとった呼び方で、これらを含む食品を控える食事療法を「低FODMAP食」といいます。<br>
  このサイトは低FODMAP食のレシピを皆様が投稿とシェアする場として作られています。
</p>

<h5 class="title mt-5 mb-3"><strong>FODMAP表（一部）</strong></h5>
<div class="container">
  <div class="row g-2 mb-3">
    <div class="col-sm">
      <div class="low">
        <h5><strong>○ 低FODMAP食</strong></h5>
        <ul>
          <li class="mb-2">米</li>
          <li class="mb-2">にんじん</li>
          <li class="mb-2">ピーマン</li>
          <li class="mb-2">レモン</li>
          <li class="mb-2">バナナ</li>
          <li class="mb-2">バター</li>
          <li class="mb-2">肉類</li>
          <li class="mb-2">魚介類</li>
          <li class="mb-2">アーモンド</li>
          <p class="mt-2">など...</p>
        </ul>
      </div>
    </div>
    <div class="col-sm">
      <div class="high">
        <h5><strong>× 高FODMAP食</strong></h5>
        <ul>
          <li class="mb-2">うどん</li>
          <li class="mb-2">パスタ</li>
          <li class="mb-2">ケーキ</li>
          <li class="mb-2">玉ねぎ</li>
          <li class="mb-2">りんご</li>
          <li class="mb-2">牛乳</li>
          <li class="mb-2">ソーセージ</li>
          <li class="mb-2">納豆</li>
          <li class="mb-2">キムチ</li>
          <p class="mt-2">など...</p>
        </ul>
      </div>
    </div>
  </div>
</div>
<small><strong><%= link_to "すべて見る＞", foods_index_path, class:"view mr-5 mb-5", style:"color: #DBB34E;" %></strong></small>
<div class="pb-4"></div>

<div class="mt-5 mb-3 title">
  <span class="h5"><strong><%= link_to "新着のレシピ", recipes_path %></strong></span>
</div>
<div class="scr">
  <div class="box-mini">
    <% @new.each do |r| %>
      <%= link_to r do %>
        <div class="box-content">
          <%= image_tag r.image.url, class:"recipe-photo" %>
          <p class="recipe-title"><%= r.title %></p>
          <div class="ingredient-box">
            <% r.ingredients.each do |i| %>
              <span><%= i.name %></span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<small><strong><%= link_to "すべて見る＞", recipes_path, class:"view mr-5", style:"color: #DBB34E;" %></strong></small>

<h5 class="mt-5 mb-3 title"><strong>人気のレシピ</strong></h5>
<div class="scr">
  <div class="box-mini">
    <% n = 1%>
    <% @ranking.each do |r| %>
      <%= link_to r do %>
      <div class="ranking-<%=n%>"><%=n%>位</div>
      <% n += 1 %>
        <div class="box-content">
          <%= image_tag r.image.url, class:"recipe-photo" %>
          <p class="recipe-title"><%= r.title %></p>
          <div class="ingredient-box">
            <% r.ingredients.each do |i| %>
              <span><%= i.name %></span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<small><strong><%= link_to "すべて見る＞", recipes_path, class:"view mr-5", style:"color: #DBB34E;" %></strong></small>