config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'homes#top'
  get 'foods/index'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  resources :users, only: [:show, :destroy]
  resources :articles, only: [:index, :show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :name, presence: true, length: {maximum: 20}
  validates :amount, presence: true, length: {maximum: 20}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :image, presence: true
  validates :title, presence: true, length: {maximum: 20}
  validates :description, presence: true, length: {maximum: 60}
  validates :people, presence: true

  belongs_to :user

  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe

  validates :number, presence: true
  validates :content, presence: true, length: {maximum: 60}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :recipes, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # deviseのuserカラムに name を追加している場合は以下のコメントアウトも追記します
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  has_many :favorites, dependent: :destroy
  has_many :myfavorites, through: :favorites, source: :recipe

  def already_favorited?(recipe)
    self.favorites.exists?(recipe_id: recipe.id)
  end

  def total_fav
    total = 0
    self.myfavorites.each do |f|
      total += f.favorites.count
    end
    return total
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @favorite = current_user.favorites.create(recipe_id: params[:recipe_id])
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
    favorite.destroy
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @new = Recipe.limit(3).order('id DESC')
    @ranking = Recipe.includes(:favorited_users).sort{|a,b| b.favorited_users.size <=> a.favorited_users.size}.first(3)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :new, :search]
  def index
    @recipes = Recipe.includes(:user).order(id: "DESC")
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.steps.build
    @recipe.ingredients.build
    unless user_signed_in?
      flash[:notice] = "レシピ投稿にはログインが必要です"
    end
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:notice] = "レシピを投稿しました"
      redirect_to @recipe
    else
      render 'recipes/new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:notice] = "レシピを更新しました"
      redirect_to @recipe
    else
      render 'recipes/edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'レシピは削除されました'
    redirect_to root_path
  end

  def search
    @keyword = params[:keyword]
    if @keyword.present?
      @recipes = Recipe.includes(:steps, :ingredients).references(:steps, :ingredients)
      @keyword.split(/[[:blank:]]+/).each do |k|
        next if k == ""
        @recipes =  @recipes.where('title like :q OR description like :q OR name like :q OR content like :q', q: "%#{k}%")
      end
    else
      @recipes = Recipe.order(id: "DESC")
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, :people, steps_attributes: [:id, :number, :content, :_destroy], ingredients_attributes: [:id, :name, :amount, :_destroy])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if current_user == @user
      @user.destroy
      flash[:notice] = "ユーザー情報は全て削除されました"
      redirect_to root_path
    else
      flash[:danger] = "不正なアクセスです"
      redirect_back (fall_back root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show mb-5" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show mb-5" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center pt-5">Copyright © Fodmaplab 2021</p>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light navshadow">
    <div class="container">
      <a class="navbar-brand" style="color: #DBB34E;" href="/">FodmapLab</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Fodmap食品一覧", foods_index_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Fodmap記事", articles_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "レシピ投稿", new_recipe_path, class: 'nav-link' %>
          </li>
        </ul>
        <div class="search_container">
          <%= form_with url: search_recipes_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, placeholder: "料理名・食材でレシピをさがす", value:@keyword %>
            <input type="submit" value="&#xf002">
          <% end %>
        </div>
        <ul class="navbar-nav mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="far fa-user-circle"></i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "マイページ", current_user, class: 'dropdown-item' %></li>
                <li><%= link_to "設定", current_user, class: 'dropdown-item' %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "無料会員登録", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fodmaplab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/83a4489301.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container parent">
      <div class="row">
        <div class="col main">
          <%= render 'layouts/flash_messages' %>
          <%= yield %>
        </div>
        <div class="col-3 side">
          <div class="ad1 text-center pt-5">広告スペース1</div>
          <div class="ad2 text-center pt-5">広告スペース2</div>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>